Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
title_to_post = "I can use more complicated code"
message_to_post = "by storing something in a variable"

reddit.subreddit(
   "soc_media_ethics_auto"
).submit(
   title_to_post, 
   selftext = message_to_tweet
)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [18][0m, in [0;36m<cell line: 4>[1;34m()[0m
[0;32m      1[0m title_to_post [38;5;241m=[39m [38;5;124m"[39m[38;5;124mI can use more complicated code[39m[38;5;124m"[39m
[0;32m      2[0m message_to_post [38;5;241m=[39m [38;5;124m"[39m[38;5;124mby storing something in a variable[39m[38;5;124m"[39m
[0;32m      4[0m reddit[38;5;241m.[39msubreddit(
[0;32m      5[0m    [38;5;124m"[39m[38;5;124msoc_media_ethics_auto[39m[38;5;124m"[39m
[0;32m      6[0m )[38;5;241m.[39msubmit(
[0;32m      7[0m    title_to_post, 
[1;32m----> 8[0m    selftext [38;5;241m=[39m [43mmessage_to_tweet[49m
[0;32m      9[0m )

[1;31mNameError[0m: name 'message_to_tweet' is not defined
NameError: name 'message_to_tweet' is not defined

