Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Give the tweepy code your developer access passwords so
# it can perform twitter actions
client = tweepy.Client(
   bearer_token=bearer_token,
   consumer_key=consumer_key, consumer_secret=consumer_secret,
   access_token=access_token, access_token_secret=access_token_secret
)

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [16][0m, in [0;36m<cell line: 3>[1;34m()[0m
[0;32m      1[0m [38;5;66;03m# Give the tweepy code your developer access passwords so[39;00m
[0;32m      2[0m [38;5;66;03m# it can perform twitter actions[39;00m
[1;32m----> 3[0m client [38;5;241m=[39m [43mtweepy[49m[38;5;241m.[39mClient(
[0;32m      4[0m    bearer_token[38;5;241m=[39mbearer_token,
[0;32m      5[0m    consumer_key[38;5;241m=[39mconsumer_key, consumer_secret[38;5;241m=[39mconsumer_secret,
[0;32m      6[0m    access_token[38;5;241m=[39maccess_token, access_token_secret[38;5;241m=[39maccess_token_secret
[0;32m      7[0m )

[1;31mNameError[0m: name 'tweepy' is not defined
NameError: name 'tweepy' is not defined

