Traceback (most recent call last):
  File "C:\Users\kmthayer\AppData\Roaming\Python\Python310\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# You can look in this file if you want to see more
# about how the file information is loaded
%run a4-supporting_code.ipynb
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [1;32mIn [5][0m, in [0;36m<cell line: 3>[1;34m()[0m
[0;32m      1[0m [38;5;66;03m# You can look in this file if you want to see more[39;00m
[0;32m      2[0m [38;5;66;03m# about how the file information is loaded[39;00m
[1;32m----> 3[0m [43mget_ipython[49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mrun_line_magic[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mrun[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43ma4-supporting_code.ipynb[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [1;32mC:\Python310\lib\site-packages\IPython\core\interactiveshell.py:2305[0m, in [0;36mInteractiveShell.run_line_magic[1;34m(self, magic_name, line, _stack_depth)[0m
[0;32m   2303[0m     kwargs[[38;5;124m'[39m[38;5;124mlocal_ns[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mget_local_scope(stack_depth)
[0;32m   2304[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mbuiltin_trap:
[1;32m-> 2305[0m     result [38;5;241m=[39m fn([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m   2306[0m [38;5;28;01mreturn[39;00m result

File [1;32mC:\Python310\lib\site-packages\IPython\core\magics\execution.py:717[0m, in [0;36mExecutionMagics.run[1;34m(self, parameter_s, runner, file_finder)[0m
[0;32m    715[0m     [38;5;28;01mwith[39;00m preserve_keys([38;5;28mself[39m[38;5;241m.[39mshell[38;5;241m.[39muser_ns, [38;5;124m'[39m[38;5;124m__file__[39m[38;5;124m'[39m):
[0;32m    716[0m         [38;5;28mself[39m[38;5;241m.[39mshell[38;5;241m.[39muser_ns[[38;5;124m'[39m[38;5;124m__file__[39m[38;5;124m'[39m] [38;5;241m=[39m filename
[1;32m--> 717[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mshell[49m[38;5;241;43m.[39;49m[43msafe_execfile_ipy[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mraise_exceptions[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[0;32m    718[0m     [38;5;28;01mreturn[39;00m
[0;32m    720[0m [38;5;66;03m# Control the response to exit() calls made by the script being run[39;00m

File [1;32mC:\Python310\lib\site-packages\IPython\core\interactiveshell.py:2811[0m, in [0;36mInteractiveShell.safe_execfile_ipy[1;34m(self, fname, shell_futures, raise_exceptions)[0m
[0;32m   2809[0m result [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mrun_cell(cell, silent[38;5;241m=[39m[38;5;28;01mTrue[39;00m, shell_futures[38;5;241m=[39mshell_futures)
[0;32m   2810[0m [38;5;28;01mif[39;00m raise_exceptions:
[1;32m-> 2811[0m     [43mresult[49m[38;5;241;43m.[39;49m[43mraise_error[49m[43m([49m[43m)[49m
[0;32m   2812[0m [38;5;28;01melif[39;00m [38;5;129;01mnot[39;00m result[38;5;241m.[39msuccess:
[0;32m   2813[0m     [38;5;28;01mbreak[39;00m

File [1;32mC:\Python310\lib\site-packages\IPython\core\interactiveshell.py:251[0m, in [0;36mExecutionResult.raise_error[1;34m(self)[0m
[0;32m    249[0m     [38;5;28;01mraise[39;00m [38;5;28mself[39m[38;5;241m.[39merror_before_exec
[0;32m    250[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39merror_in_exec [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m--> 251[0m     [38;5;28;01mraise[39;00m [38;5;28mself[39m[38;5;241m.[39merror_in_exec

    [1;31m[... skipping hidden 1 frame][0m

File [1;32m~\AppData\Local\Temp\ipykernel_38608\4014426467.py:2[0m, in [0;36m<cell line: 2>[1;34m()[0m
[0;32m      1[0m [38;5;66;03m# load the pandas code library, which helps us use the csv file[39;00m
[1;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m      4[0m [38;5;66;03m# load the media_info.csv file[39;00m
[0;32m      5[0m media_info_df [38;5;241m=[39m pd[38;5;241m.[39mread_csv([38;5;124m'[39m[38;5;124mmedia_info.csv[39m[38;5;124m'[39m)

[1;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

